### ISSUE TITLE
בעמוד "צוות הקמפיין" שהוא העמוד האחרון צריך גם כפתור שלח לאישור

### ISSUE THREAD

**Issue by nirhirshman** [codeworth-gh/HearUsPlatform#104]
שיפור: כפתור ״שלח לאישור״ בכל עמוד של ניהול הקמפיין.

**Comment by michbarsinai** [comment]
הכפתור התווסף למסך ״פרטים״, שמציג את הנתונים הכללים של הקמפיין. בעבר היה רק בטבלת ״הקמפיינים שלי״.
