### ISSUE TITLE
רווח מיותר בין הכותרת לטקסט

### ISSUE THREAD

**Issue by nirhirshman** [codeworth-gh/HearUsPlatform#105]
![image](https://user-images.githubusercontent.com/15030893/83386228-5532e280-a3f3-11ea-97b2-903365516b69.png)

**Comment by michbarsinai** [comment]
כנראה ענייני עיצוב של הדף

**Comment by michbarsinai** [comment]
נובע מעיצוב ה-
sections
 כך שתופסות  גודל חלון.

דורש עיצוב מחדש
