### ISSUE TITLE
בדף "עמוד ראשי" לבטל את אופציות העיצוב

### ISSUE THREAD

**Issue by nirhirshman** [codeworth-gh/HearUsPlatform#106]
אפשר ממש להכניס כאן כעת html 
מוצע שתהיה אפשרות להכניס רק plain text 
ושזה יכניס את הטקסט לאתר בעיצוב של האתר בלבד
![image](https://user-images.githubusercontent.com/15030893/83386704-25380f00-a3f4-11ea-80f8-9f7595fd9be9.png)

**Comment by nirhirshman** [comment]
זה בעדיפות נמוכה. אני שם את זה כאן כדי שלא נשכח

**Comment by michbarsinai** [comment]
להסתיר את דף העיצוב.

בדף ראשי, להשאיר רק הדגשות, קו תחתי, ולינקים למיניהם.
