### ISSUE TITLE
הערת לקוח: הם צריכים לדעת כמה פעמים לחצו על הלינק של וואטסאפ, טוויטר, פייס, מייל וכו

### ISSUE THREAD

**Issue by nirhirshman** [codeworth-gh/HearUsPlatform#107]
בפועל הם היו רוצים לדעת כמה נשלח, אבל זה מספיק טוב לדעת כמה פעמים נלחץ הלינק
![image](https://user-images.githubusercontent.com/15030893/83424324-eb3b2d00-a434-11ea-9781-a5643265f7a5.png)

**Comment by michbarsinai** [comment]
Dup #118
