### ISSUE TITLE
דו״חות לקמפיינרים

### ISSUE THREAD

**Issue by michbarsinai** [codeworth-gh/HearUsPlatform#118]
כמה מסרים נשלחו,
למי
מתי (לפי שעות)

**Comment by nirhirshman** [comment]
פר קמפיין- כמה קליקים וואטסאפ, כמה טוויטר כמה מייל כמה ג'ימייל וכמה פייסבוק 
אין צורך בחלוקה לחכי"ם

**Comment by michbarsinai** [comment]
Can be a CSV report, per campaign.
Columns:
* Time
* MK
* Contact type
* Full contact details

**Comment by nirhirshman** [comment]
קריטי: 2
קלות: 2
