### ISSUE TITLE
סניפט מושך תמונה רנדומלית של חברת כנסת

### ISSUE THREAD

**Issue by nirhirshman** [codeworth-gh/HearUsPlatform#150]
![image](https://user-images.githubusercontent.com/15030893/86004171-8ff06080-ba1b-11ea-80dc-2719f991e058.png)
הוא צריך למשוך נניח את התמונה של הריבועים של כל חברי הכנסת

**Comment by michbarsinai** [comment]
אמור להיות פתור עכשיו (תמונה מהדיבאגגר של פייסבוק)

![image](https://user-images.githubusercontent.com/1938468/86063286-3a47a280-ba73-11ea-969e-bca6f5b6563c.png)
