### ISSUE TITLE
Check if the Knesset OpenAPI have twitter, facebook, and other social accounts

### ISSUE THREAD

**Issue by michbarsinai** [codeworth-gh/HearUsPlatform#44]
Note that the official knesset site does have them(e.g. in https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=860, when you scroll down).

**Comment by MorVilozni** [comment]
24/7/19 - can't find social accounts at OData (http://knesset.gov.il/Odata/ParliamentInfo.svc/)
