### ISSUE TITLE
כשפותחים קמפיין חדש, דף המסרים טוען בלי הפסקה ולא נותן לעבוד על דף המסרים

### ISSUE THREAD

**Issue by michbarsinai** [codeworth-gh/HearUsPlatform#45]
הבעיה קיימת רק למי שהוא משתתף בקמפיין ולא מוגדר כמנהל. כדאי אולי להעלות הודעה כאשר משתתף לוחץ על דף המסרים שאין לו הרשאה במקום שזה יטען הרבה זמן כמו שקורה עכשיו.

**Comment by MorVilozni** [comment]
לא הצלחנו לשחזר, מחכים להבהרות

**Comment by michbarsinai** [comment]
נא לרשום מה שיותר פרטים - דפדפן, גרסת מערכת הפעלה, סוג חיבור לאינטרנט, וכד׳

**Comment by omer-danino-nirshman** [comment]
MICROSOFT EDGE: דפדפן
מערכת הפעלה: ווינדוס 10
WI-FI :סוג חיבור לאינטרנט 

אם יש צורך בעוד משהו אז תגידו.
הוספתי תמונה של איך זה נראה אם במקרה זה לא מובן.
![‏‏לכידה](https://user-images.githubusercontent.com/53428931/62038564-a7690d00-b1fe-11e9-9a52-2c20f96977c7.JPG)

**Comment by MorVilozni** [comment]
לא הצלחתי לשחזר בווינדוס 10, באותו דפדפן, בתור משתתפת

![Screenshot from 2019-08-05 15-39-29](https://user-images.githubusercontent.com/11991887/62465331-478edb00-b797-11e9-9736-97d5f89da50d.png)

**Comment by omer-danino-nirshman** [comment]
![חיתוך](https://user-images.githubusercontent.com/53428931/63221544-38e6f180-c1a3-11e9-95bd-82fd3c63219b.JPG)

**Comment by michbarsinai** [comment]
Test this:

````Javascript
Promise.prototype.finally = Promise.prototype.finally || {
  finally (fn) {
    const onFinally = cb => Promise.resolve(fn()).then(cb);
    return this.then(
      result => onFinally(() => result),
      reason => onFinally(() => Promise.reject(reason))
    );
  }
}.finally;
````
