### ISSUE TITLE
צריך ערך דיפולטי בדף עמדות

### ISSUE THREAD

**Issue by nirhirshman** [codeworth-gh/HearUsPlatform#66]
עדיף שיהיה לא החליט 
כמוכן, צריך אפשרות לעריכה קבוצתית על פי מפלגות

![image](https://user-images.githubusercontent.com/15030893/64109789-15b66780-cd89-11e9-98ce-8a66ca9d4948.png)

**Comment by michbarsinai** [comment]
עריכה לפי מפלגות - להמתין לאפיון/הקצאה

**Comment by nirhirshman** [comment]
לא הבנתי? למה הכוונה להמתין לאפיון /הקצאה?

**Comment by MorVilozni** [comment]
- [ ] Add default value
- [ ] Enable to edit group of KMs

**Comment by michbarsinai** [comment]
ניתן לערוך מפלגה על ידי סינון הרשימה לפי שם המפלגה, ואז סימון הח״כים.
