### ISSUE TITLE
מזהה יחודי (סלאג) שיבחר באופן אוטומטי

### ISSUE THREAD

**Issue by nirhirshman** [codeworth-gh/HearUsPlatform#71]
כרגע שנכנסים לבניית קמפיין הדיפולט הוא הכתובת של המערכת ואז אתה צריך לתת שם. זה משהו שמתבלבלים בו. בבקשה שהמערכת תבחר סלאג לכל קמפיין ייחודי ושלום על ישראל

**Comment by michbarsinai** [comment]
צריך לחשוב על זה, סלאג דיפולטי כזה יראה כמו 
`5e194d7e-cda9-11e9-9604-535e80d49317`
או אפילו סתם
`13ff54aC3`

(שזה קצת בעייתי כי אפשר לסרוק את כולם.)

לדעתי אפשר להשאיר כמו שזה, בתכל׳ס קמפיינרים צריכים לחשוב על הרבה ניסוחים גם ככה, שיחשבו על עוד אחד.

**Comment by nirhirshman** [comment]
שמע, זה לא משמעותי. שיתן פשוט סלאג, ואם אפשר לא עוקב. כמוכן, מה איכפת לי אם יסרקו את כולם? גם ככה זה פתוח לצבור. שיהיה להם בהצלחה, אנחנו לא מחביאים דבר
