### ISSUE TITLE
המערכת לא מעתיקה את תוכן המייל לג'ימייל

### ISSUE THREAD

**Issue by nirhirshman** [codeworth-gh/HearUsPlatform#73]
היא למעשה מעתיקה רק את הכותרת של הקמפיין שזו בכלל לא הכותרת של המייל

ומעבר להכל זה באג מאז'ורי מאווודדדדד

![image](https://user-images.githubusercontent.com/15030893/64122756-28419880-cdab-11e9-8c9c-961a557d0a9f.png)

**Comment by michbarsinai** [comment]
יותר כמו שגיאה באיפיון - אין כרגע בכלל שורת כותרת למייל... יטופל

**Comment by michbarsinai** [comment]
בדקנו בכרום, פיירפוקס, אדג׳, וספארי. עובד בכולם.

**Comment by nirhirshman** [comment]
אופרה?
ניר הירשמן
050-6205384
בקרו אותנו ב- http://nirshman.com


‫בתאריך יום א׳, 15 בספט׳ 2019 ב-11:37 מאת ‪Michael‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by michbarsinai** [comment]
Whoa. HARDCORE!

**Comment by michbarsinai** [comment]
גם אופרה עובד

<img width="740" alt="image" src="https://user-images.githubusercontent.com/1938468/64919098-a3457e80-d7af-11e9-94f3-df3c2bc03a08.png">

**Comment by nirhirshman** [comment]
פיצוץ
ניר הירשמן
050-6205384
בקרו אותנו ב- http://nirshman.com


‫בתאריך יום א׳, 15 בספט׳ 2019 ב-11:55 מאת ‪Michael‬‏ <‪
notifications@github.com‬‏>:‬
