### ISSUE TITLE
אפשרות לפתוח יוזרים חדשים

### ISSUE THREAD

**Issue by nirhirshman** [codeworth-gh/HearUsPlatform#74]
אני צריך אפשרות לפתוח יוזרים חדשים בבקשה

**Comment by michbarsinai** [comment]
הם יכולים להרשם לאתר בעצמם, ואז אתה יכול לסמן אותם בתור מנהלים באתר הניהול:
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/1938468/64128664-48c81d80-cdc0-11e9-8502-614c95f405c8.png">

**Comment by nirhirshman** [comment]
תראה לי איך הם יכולים להירשם בבקשה?
ניר הירשמן
050-6205384
בקרו אותנו ב- http://nirshman.com


‫בתאריך יום ב׳, 2 בספט׳ 2019 ב-20:29 מאת ‪Michael‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by michbarsinai** [comment]
אפשרות ראשונה: להזמין לפי מייל מהבק-אופיס:
<img width="963" alt="image" src="https://user-images.githubusercontent.com/1938468/64174752-97c68f00-ce62-11e9-9397-471033ff9a43.png">

אפשרות שניה: שיצטרפו בעצמם מהדף הציבורי באתר:
<img width="813" alt="image" src="https://user-images.githubusercontent.com/1938468/64174835-baf13e80-ce62-11e9-8876-3199edceb4d8.png">

**Comment by nirhirshman** [comment]
צריך אז כפתור "התחל קמפיין"
ניר הירשמן
050-6205384
בקרו אותנו ב- http://nirshman.com


‫בתאריך יום ג׳, 3 בספט׳ 2019 ב-15:51 מאת ‪Michael‬‏ <‪
notifications@github.com‬‏>:‬
