### ISSUE TITLE
can't edit link to party

### ISSUE THREAD

**Issue by nirhirshman** [codeworth-gh/HearUsPlatform#84]
![image](https://user-images.githubusercontent.com/15030893/82186245-36145b00-98f3-11ea-9411-d27317a43fec.png)

**Comment by michbarsinai** [comment]
צריך ללחוץ על כפתור ״עריכה״. אחרי זה לשנות, ואז ללחוץ ״שמירה״.

בגרסה החדשה הממשק יותר בהיר בנושא.

<img width="864" alt="image" src="https://user-images.githubusercontent.com/1938468/82487148-a505d580-9ae6-11ea-8016-fa841c84154d.png">
