### ISSUE TITLE
usama saadi to black

### ISSUE THREAD

**Issue by nirhirshman** [codeworth-gh/HearUsPlatform#88]
![image](https://user-images.githubusercontent.com/15030893/82294147-59540e80-99b6-11ea-8ef8-bfe1b639de17.png)

**Comment by michbarsinai** [comment]
@nirhirshman Can you please send the original pic?

**Comment by nirhirshman** [comment]
![Osama_Saadi](https://user-images.githubusercontent.com/15030893/82422626-5bd46800-9a8b-11ea-8259-5f63ffab499f.jpg)
![Launch_of_'British_Club'_for_Holocaust_survivors_(6885477889)_(cropped)](https://user-images.githubusercontent.com/15030893/82422632-5d059500-9a8b-11ea-9dce-6855e719bb59.jpg)

**Comment by michbarsinai** [comment]
in the algorithm's defense, these pictures need more than just histogram stretch. Implemented manually with GIMP :-)
