### ISSUE TITLE
Google analytics

### ISSUE THREAD

**Issue by nirhirshman** [codeworth-gh/HearUsPlatform#90]
We need analytics for us to control

**Comment by michbarsinai** [comment]
Supported  by Google, so we can do this and have campaigns have their analytics too:
https://support.google.com/analytics/answer/1032400?hl=en

**Comment by nirhirshman** [comment]
לא הבנתי כלום

**Comment by michbarsinai** [comment]
סתם מסמן לעצמי שאפשר גם אנליטיקס שלנו וגם של הקמפיין :-)

**Comment by nirhirshman** [comment]
סבבה

בתאריך יום ד׳, 20 במאי 2020, 14:59, מאת Michael ‏<notifications@github.com>:
