### ISSUE TITLE
click on facebook links is broken

### ISSUE THREAD

**Issue by nirhirshman** [codeworth-gh/HearUsPlatform#95]
for example:
https://hear-us.mbarsinai.com/campaigns/TfKVPCaNB/KnessetMembers/347

the link leads to https://www.facebook.com/https://www.facebook.com/ShayIzhar/

![image](https://user-images.githubusercontent.com/15030893/82552323-88ab7c80-9b6a-11ea-9f63-3bdbd522ff7d.png)

**Comment by michbarsinai** [comment]
צריך להכניס שם משתמש, ולא את כתובת דף הפייסבוק/טוויטר
תיקנתי את יזהר שי בתור דוגמא

**Comment by nirhirshman** [comment]
עכשיו אתה אומר?

**Comment by nirhirshman** [comment]
אי אפשר לעשות את זה שהמערכת תקצוץ את זה אוטומטית? זה גיהנום! חמישה ימים ברצף עבדנו על זה!

**Comment by michbarsinai** [comment]
ננסה :-)

**Comment by michbarsinai** [comment]
Done
