### ISSUE TITLE
click on twitter links derives the twitter link and not the twitter handle

### ISSUE THREAD

**Issue by nirhirshman** [codeworth-gh/HearUsPlatform#96]
It won't be tagged this way
![image](https://user-images.githubusercontent.com/15030893/82552441-c7d9cd80-9b6a-11ea-9939-5302bf38fed9.png)

**Comment by nirhirshman** [comment]
that comes from here:
![image](https://user-images.githubusercontent.com/15030893/82552526-f061c780-9b6a-11ea-9725-335953bad42b.png)

**Comment by michbarsinai** [comment]
צריך להכניס שם משתמש, ולא את כתובת דף הפייסבוק/טוויטר
תיקנתי את יזהר שי בתור דוגמא

**Comment by nirhirshman** [comment]
לא אבל זה עכישו לעבור על הכל מחדש

**Comment by nirhirshman** [comment]
רגע מיכאל אז אנחנו צריכים לעשות כאן איזה שינוי. יש אפשרות לטעון קבצי אקסל או CSV לתוך הדטהבייס ישירות? כי לעבוד מול הממשק זה גיהנום

**Comment by michbarsinai** [comment]
Done :-)
