### ISSUE TITLE
כאשר מנסים לעבור דף לפני שמירה- המערכת חייבת להתריע!

### ISSUE THREAD

**Issue by nirhirshman** [codeworth-gh/HearUsPlatform#97]
כרגע היא פשוט מוחקת את התוכן זה דיכאון מחץ

**Comment by nirhirshman** [comment]
לשון ההתראה:

רוצים לעבור דף? ליחצו על שמירה או שהנתונים יאבדו לנצח!
ביטול/מחיקת נתונים

**Comment by michbarsinai** [comment]
יש כבר דפים בהם אנחנו עושים את זה. באיזה דף זה קרה?

**Comment by nirhirshman** [comment]
מסרים, עיצוב, עמוד ראשי. הכל עובר ולא שומר

בתאריך יום א׳, 31 במאי 2020, 11:32, מאת Michael ‏<notifications@github.com>:

**Comment by michbarsinai** [comment]
מקרים לא מכוסים כרגע:

* טקסט לא שמור במסרים

**Comment by michbarsinai** [comment]
עמוד ראשי - עובד

פרטים - עובד

עמדות, ועדות וצוות - לא רלוונטי כי אין שם שדות
