### ISSUE TITLE
 מסרים לא נשמרים וכל המסרים שהוכנסו בעבר נעלמו

### ISSUE THREAD

**Issue by nirhirshman** [codeworth-gh/HearUsPlatform#98]
כשאתה מנסה לשמור הוא נתקע על גלגל השיניים אבל יותר מזה- אין את כל המסרים שהכנסנו בעבר. כאילו הוא לא מחובר לדטה בייס או משהו. אני מצרף צילומי מסך להבהרה:
המצב בשמירה:
![image](https://user-images.githubusercontent.com/15030893/83347428-b2646080-a32d-11ea-9af3-948d5f085949.png)
המסרים נעלמו. זה דף שבו הכנסתי מסרים וכעת הם פשוט לא קיימים
![image](https://user-images.githubusercontent.com/15030893/83347461-e2136880-a32d-11ea-8ca0-261be1c89203.png)

**Comment by nirhirshman** [comment]
![image](https://user-images.githubusercontent.com/15030893/83347733-a5487100-a32f-11ea-92e2-9cd0d670ac49.png)

**Comment by nirhirshman** [comment]
שמתי לך כאן צילומסך של הקונסולה שביקשת

**Comment by nirhirshman** [comment]
לא עובד גם בפיירפוקס
![image](https://user-images.githubusercontent.com/15030893/83349977-599ec300-a341-11ea-910a-ea3cf084b6e3.png)
גרסת פיירפוקס:
![image](https://user-images.githubusercontent.com/15030893/83350004-97035080-a341-11ea-855e-a6538c4d631c.png)

**Comment by michbarsinai** [comment]
Replaced `replaceAll` with a more compliant code.
